# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repowalk < Formula
  desc "A blazing-fast, interactive CLI tool that walks your repository and packs it into a Markdown document for LLMs."
  homepage "https://github.com/QubeUtils/repowalk"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Darwin_x86_64.tar.gz"
      sha256 "f33d4aba66cf34eac5851bad7774eaba9a7f53a31433a40748403dc0e8fff5de"

      define_method(:install) do
        bin.install "repowalk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Darwin_arm64.tar.gz"
      sha256 "60bbd317c521ed8e1a6a28210cbd9a2cec409d0ce48f51011372b310a89c6407"

      define_method(:install) do
        bin.install "repowalk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Linux_x86_64.tar.gz"
      sha256 "aa1164d16263c38dfcce91868c9eb3caeaea952e4f92eb28a3c88bda8dfd7135"
      define_method(:install) do
        bin.install "repowalk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Linux_arm64.tar.gz"
      sha256 "b7e1615d55c7d682310e29ef6c6a3da9f9d2bbad28bc0232ac62723f59e89110"
      define_method(:install) do
        bin.install "repowalk"
      end
    end
  end

  test do
    system "#{bin}/repowalk --help"
  end
end
