# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repowalk < Formula
  desc "A blazing-fast, interactive CLI tool that walks your repository and packs it into a Markdown document for LLMs."
  homepage "https://github.com/QubeUtils/repowalk"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Darwin_x86_64.tar.gz"
      sha256 "c67c02b238f30b7b5fe81aca10d4eeeeb6a00c28a8427365774b969e4bcaca96"

      define_method(:install) do
        bin.install "repowalk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Darwin_arm64.tar.gz"
      sha256 "fc8eb7e5cccc3665b38b3264974ddd40fbc741b5dd43fa9c041e09115148530c"

      define_method(:install) do
        bin.install "repowalk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Linux_x86_64.tar.gz"
      sha256 "d57614534044dc8dc01e2131dbec061b6b4dc43e457d6da11329d9db4c16a6ae"
      define_method(:install) do
        bin.install "repowalk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.1.2/repowalk_Linux_arm64.tar.gz"
      sha256 "e803763c352438500af428695c6637a23e3372775ecc8b2d228b076dbc8ce381"
      define_method(:install) do
        bin.install "repowalk"
      end
    end
  end

  test do
    system "#{bin}/repowalk --help"
  end
end
