# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repowalk < Formula
  desc "A blazing-fast, interactive CLI tool that walks your repository and packs it into a Markdown document for LLMs."
  homepage "https://github.com/QubeUtils/repowalk"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.2.0/repowalk_Darwin_x86_64.tar.gz"
      sha256 "b1dbe2d9e17e3763c4cbd6382b04e1550913c0122ac9bca070741a90cd1d6ae2"

      define_method(:install) do
        bin.install "repowalk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.2.0/repowalk_Darwin_arm64.tar.gz"
      sha256 "f7d56c4196100bd01e2dcbc47b6a71307734df7aad848e0078d992f7a82e1026"

      define_method(:install) do
        bin.install "repowalk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.2.0/repowalk_Linux_x86_64.tar.gz"
      sha256 "8a721aa3ab6655db84bb30c17b3a211b6351896974499de79e5dc8b3a809f832"
      define_method(:install) do
        bin.install "repowalk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QubeUtils/repowalk/releases/download/v0.2.0/repowalk_Linux_arm64.tar.gz"
      sha256 "3a35576faf90052a8447a3cf42b31d676b681c215dc98b65c8b1c4ba3659a8b1"
      define_method(:install) do
        bin.install "repowalk"
      end
    end
  end

  test do
    system "#{bin}/repowalk --help"
  end
end
